language: node_js
node_js:
  - '7'

sudo: required

# Cache npm inbetween builds to improve build time
# Documentaion - https://docs.travis-ci.com/user/caching/
cache:
  directories:
  - node_modules # NPM packages

# registering to user postgresql database
services:
  - postgresql

# creates the database
before_install:
  - psql -c 'create database pwadb;' -U postgres

# Deploy
# Bluemix
deploy:
  edge: true
  provider: cloudfoundry
  username: ${BLUEMIX_USER}
  #########################
  ## Add BLUEMIX_PASSWORD environment variable to your Travis project's settings
  ## https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings
  #########################
  password: ${BLUEMIX_PASSWORD}
  organization: ${BLUEMIX_USER}
  space: dev
  api: https://api.ng.bluemix.net/
  on:
    branch: master

# Deploy
# Openshift
# deploy:
#   provider: openshift
#   user: ${OPENSHIFT_USER}
#   password: ${OPENSHIFT_PASSWORD}
#   app: nodejs
#   domain: ${OPENSHIFT_DOMAIN}
#   on:
#     repo: sinnott74/Node-Web-App